### ISSUE TITLE
Service is being killed right away

### ISSUE THREAD

**Issue by Gutyn** [codemotionapps/react-native-dark-mode#28]
I keep seeing:
`W/ActivityManager: Scheduling restart of crashed service com.mycompany.myapp/com.codemotionapps.reactnativedarkmode.DarkModeService in 1000ms
I/ActivityManager:   Force stopping service ServiceRecord{55c1c4c u0 com.mycompany.myapp/com.codemotionapps.reactnativedarkmode.DarkModeService}
`

And the `onConfigurationChanged` is never called.
Please let me know if I'm missing something.

**Comment by Gutyn** [comment]
@dimitarnestorov am I missing something? Do I need to add anything to the project AndroidManifest or this should work as-is.

**Comment by DimitarNestorov** [comment]
Tell me more about your environment. Which version of RN are you using?

**Comment by Gutyn** [comment]
Thanks for the quick response:
```System:
    OS: macOS 10.15
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 30.52 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by DimitarNestorov** [comment]
Can you try Android Studio 3.6 Canary?

**Comment by Gutyn** [comment]
@dimitarnestorov Just tried that and it resulted in the same problem.
I assume the service does not need any other setup, it should just work?

**Comment by Gutyn** [comment]
@dimitarnestorov quick observation, it actually works if I add the darkTheme setting in the quick setting and don't switch the app for the settings app to change the darktheme mode, it still crashes eventually but, is it intended to only work if the app is in the foreground? You can't background it and go to the actual darkTheme setting?

**Comment by DimitarNestorov** [comment]
The service should just work.
The service may not work in the background since changes required by #22 and #23. 
Try version 0.1.0 (don't try 0.1.1) and report results.

**Comment by Gutyn** [comment]
@dimitarnestorov just tested 0.1.0 and it works well, thank you.

**Comment by DimitarNestorov** [comment]
It works well for you, but sadly that's not a good solution. Using that version will make your app crash on other users' phones. I'll need to figure out something better.

**Comment by Gutyn** [comment]
I see, ok I will let you know if I come across an idea.

**Comment by taschik** [comment]
We installed ~~0.1.0~~ 0.1.2 and most of the crashes are gone, however we see a new one popping us:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.xxxx/com.xxx.MainActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx/com.codemotionapps.reactnativedarkmode.DarkModeService }: app is in background uid UidRecord{14d4823 u0a282 TRNB bg:+5h14m22s521ms idle change:uncached procs:1 proclist:21556, seq(0,0,0)}
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4013)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4045)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:183)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx/com.codemotionapps.reactnativedarkmode.DarkModeService }: app is in background uid UidRecord{14d4823 u0a282 TRNB bg:+5h14m22s521ms idle change:uncached procs:1 proclist:21556, seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
       at android.app.ContextImpl.startService(ContextImpl.java:1611)
       at android.content.ContextWrapper.startService(ContextWrapper.java:677)
       at com.codemotionapps.reactnativedarkmode.DarkModeModule.onHostResume(DarkModeModule.java:70)
       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:208)
       at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:661)
       at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:580)
       at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:536)
       at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:105)
       at com.facebook.react.ReactActivity.onResume(ReactActivity.java:64)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
       at android.app.Activity.performResume(Activity.java:7558)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4005)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4045)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:183)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

Any idea?

**Comment by Gutyn** [comment]
@taschik take a look at this maybe:
https://stackoverflow.com/a/47654126/3211679

**Comment by DimitarNestorov** [comment]
@taschik That's what 0.1.2 aimed to fix

**Comment by taschik** [comment]
I have to correct myself. This crash happens on `0.1.2`,  I was on the wrong branch when I looked it up. Are you sure this released fixed it?

**Comment by DimitarNestorov** [comment]
Looks like there's one more edge case, great 🙃. Will try to bind the service to the React activity and hopefully avoid all crashes.

**Comment by taschik** [comment]
haha thanks for trying to fix. You are doing a great job! Thanks!

**Comment by DimitarNestorov** [comment]
[0.2.0-rc.0 released](https://www.npmjs.com/package/react-native-dark-mode/v/0.2.0-rc.0)
I totally removed the service 🥳, however this came with a cost, no more support for RN 0.59, it may work with [reverse jetifier](https://medium.com/developer-circle-kampala/how-to-delay-android-x-migrations-with-react-native-by-ronald-kasendwa-f84e6c43530c) but I haven't tested it yet.
Please test, I would love to close this issue!
```
npm install react-native-dark-mode@next
```
```
yarn add react-native-dark-mode@next
```

**Comment by taschik** [comment]
Cool @dimitarnestorov , you are amazing. Will give it a test and ship the next update with it. Will let you know if the crash reoccurs.

**Comment by Ashoat** [comment]
Seeing [this build failure](https://gist.github.com/Ashoat/684dd44c090956fc1b5a6ad245847737) on Android with the new 0.2.0-rc.0, tried using both autolinking and `react-native link`

**Comment by manuhook** [comment]
Hi @dimitarnestorov ! same error as @Ashoat when building : 
`D8: Program type already present: com.facebook.react.ReactActivity`

**Comment by DimitarNestorov** [comment]
0.2.0-rc.1 released
You guys also might be interested in this: [Prevent Android app from restarting when dark mode changes](https://github.com/codemotionapps/react-native-dark-mode#prevent-android-app-from-restarting-when-dark-mode-changes)

**Comment by manuhook** [comment]
Thanks 👍 Build is fixed, I will let you know if I see any exception !

**Comment by Ashoat** [comment]
Awesome!! Android build is fixed, and is now picking up changes instantaneously, while backgrounded, without auto-restarting or requiring a restart. Thanks for the hard work!

**Comment by Gutyn** [comment]
@dimitarnestorov thank you for the quick fix, great work.

**Comment by humbkr** [comment]
@dimitarnestorov Thanks for your work, it would be great to update the readme about RN 0.59 dropped support so others don't waste time, I had to find this issue to have the information.

**Comment by DimitarNestorov** [comment]
@humbkr It's not in the README, because that is not the case. After that comment I rewrote the Android code and last time I tested the module is working with 0.59. You can also try https://github.com/expo/react-native-appearance if you can't get it to work.
